[package]
name = "linked-list"
version = "0.1.0"
authors = ["Craig Bruce <craig@craig-bruce.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
